### ISSUE TITLE
Setup if savedir is not relative to dokuwiki defined

### ISSUE THREAD

**Issue by idefix6** [woolfg/dokuwiki-plugin-gitbacked#26]
Hi,

I have some problems getting the plugin running.
My setup is:
dokuwiki installed in /usr/local/www/dokuwiki
data in /usr/local/dokuwiki-data

The directory is in the setings defined with:
$conf['savedir'] = '/usr/local/dokuwiki-data';

But it seems that the plugin will not work, I tried several configuration combinations.
If I put an absolute path for datadir and mediadir it will display the wiki again, but I cannot edit pages anymore as the commit seems to fail.

Thanks for tips,
Matthias

**Comment by woolfg** [comment]
are there any error messages (if you enable php error reporting) or error-messages in the httpd log

**Comment by idefix6** [comment]
Following set in conf/local.php:
```
$conf['savedir'] = '/usr/local/dokuwiki-data';
$conf['plugin']['gitbacked']['repoPath'] = '/usr/local/dokuwiki-data/gitrepo';
$conf['plugin']['gitbacked']['repoWorkDir'] = '/usr/local/dokuwiki-data/gitrepo/wiki';
$conf['datadir'] = '/usr/local/dokuwiki-data/gitrepo/wiki/pages';
$conf['mediadir'] = '/usr/local/dokuwiki-data/gitrepo/wiki/media';
```

Error message is:
```
[Mon Jul 27 19:53:14.746413 2015] [:error] [pid 3903:tid 34552767488] [client ::1:54404] FastCGI: server "/usr/local/www/fastcgi/php5.fastcgi" stderr: PHP message: PHP Fatal error:  Uncaught exception 'Exception' with message 'cannot create repository in non-existent directory' in /usr/local/www/dokuwiki/lib/plugins/gitbacked/lib/Git.php:223, referer: https://wiki.idefix.fechner.net/doku.php/test?do=edit
[Mon Jul 27 19:53:14.746475 2015] [:error] [pid 3903:tid 34552767488] [client ::1:54404] FastCGI: server "/usr/local/www/fastcgi/php5.fastcgi" stderr: Stack trace:, referer: https://wiki.idefix.fechner.net/doku.php/test?do=edit
[Mon Jul 27 19:53:14.746557 2015] [:error] [pid 3903:tid 34552767488] [client ::1:54404] FastCGI: server "/usr/local/www/fastcgi/php5.fastcgi" stderr: #0 /usr/local/www/dokuwiki/lib/plugins/gitbacked/lib/Git.php(172): GitRepo->set_repo_path('/usr/local/www/...', true, true), referer: https://wiki.idefix.fechner.net/doku.php/test?do=edit
[Mon Jul 27 19:53:14.746583 2015] [:error] [pid 3903:tid 34552767488] [client ::1:54404] FastCGI: server "/usr/local/www/fastcgi/php5.fastcgi" stderr: #1 /usr/local/www/dokuwiki/lib/plugins/gitbacked/action/editcommit.php(44): GitRepo->__construct('/usr/local/www/...', true, true), referer: https://wiki.idefix.fechner.net/doku.php/test?do=edit
[Mon Jul 27 19:53:14.746617 2015] [:error] [pid 3903:tid 34552767488] [client ::1:54404] FastCGI: server "/usr/local/www/fastcgi/php5.fastcgi" stderr: #2 /usr/local/www/dokuwiki/lib/plugins/gitbacked/action/editcommit.php(76): action_plugin_gitbacked_editcommit->initRepo(), referer: https://wiki.idefix.fechner.net/doku.php/test?do=edit
[Mon Jul 27 19:53:14.746651 2015] [:error] [pid 3903:tid 34552767488] [client ::1:54404] FastCGI: server "/usr/local/www/fastcgi/php5.fastcgi" stderr: #3 /usr/local/www/dokuwiki/lib/plugins/gitbacked/action/editcommit.php(192): action_plugin_gitbacked_editcommit->commitFile('/usr/local/doku...', 'Wiki page test ...'), referer: https://wiki.idefix.fechner.net/doku.php/test?do=edit
[Mon Jul 27 19:53:14.746685 2015] [:error] [pid 3903:tid 34552767488] [client ::1:54404] FastCGI: server "/usr/local/www/fastcgi/php5.fastcgi" stderr: #4 /usr/local/www/dokuwiki/inc/events.php(204): action_plugin_gitbacked_editcommit->handle_io_wikipage_write(Object(Doku_Event), NULL), referer: https://wiki.idefix.fechner.net/doku.php/test?do=edit
[Mon Jul 27 19:53:14.746709 2015] [:error] [pid 3903:tid 34552767488] [client ::1:54404] FastCGI: server "/usr/local/www/fastcgi/php5.fastcgi" stderr: #5 /usr/local/www/dokuwiki/inc/events.php(76): Doku_Event_Handler->process_event(Object(Doku_Event), 'AFTER'), referer: https://wiki.idefix.fechner.net/doku.php/test?do=edit
[Mon Jul 27 19:53:14.746742 2015] [:error] [pid 3903:tid 34552767488] [client ::1:54404] FastCGI: server "/usr/local/www/fastcgi/php5.fastcgi" stderr: #6 /usr/local/www/dokuw..., referer: https://wiki.idefix.fechner.net/doku.php/test?do=edit
```
The directory /usr/local/dokuwiki-data/gitrepo is writeable by the www user:
```
1 drwxr-xr-x   3 www  wheel   3 Jul 27 19:37 .
9 drwxr-xr-x  11 www  wheel  15 Jul 27 19:38 ..
1 drwxr-xr-x   4 www  wheel   4 Jul 27 19:38 wiki
```

**Comment by woolfg** [comment]
try to use a relative git location. the errors show that '/usr/local/www/...' is accessed.

**Comment by idefix6** [comment]
If I set the following it is working:
```
$conf['plugin']['gitbacked']['repoPath'] = '../../../dokuwiki-data/gitrepo';
$conf['plugin']['gitbacked']['repoWorkDir'] = '../../../dokuwiki-data/gitrepo/wiki';
```
But I do not like this. Is it possible to fix this bug?

**Comment by woolfg** [comment]
It's not a bug. Typical setups use a path below the wiki base dir, therefore I used a relative path. If you want support for relative and absolute paths, some checks are needed. It would be great if you can implement this feature and add by using a pull request.
