### ISSUE TITLE
"Exception: *** Please tell me who you are..."

### ISSUE THREAD

**Issue by lex111** [woolfg/dokuwiki-plugin-gitbacked#36]
Hello,

When you try to edit a page, I get an exception, although the name and e-mail for a given git in .gitconfig. Why then this error?

http://prntscr.com/bwxvqx

**Comment by woolfg** [comment]
the config has to be defined for the user that executes the command (e.g. user of apache or php)

**Comment by lex111** [comment]
Thank you, have a repository name and e-mail, the error disappeared. Just I expect that if the settings are not set locally, they will be taken from the global config.

**Comment by lastwednesday** [comment]
I am really struggling with this so far. I have user.name and user.email configured globally, and have also copied that .gitconfig file to /var/www/ which is home directory for www-data user which is running lighttpd. But I am still facing this error.
Is there a step I am missing?

2016-12-25 21:19:23: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Fatal error:  Uncaught exception 'Exception' with message '
2016-12-25 21:19:23: (mod_fastcgi.c.2702) FastCGI-stderr: *** Please tell me who you are.
2016-12-25 21:19:23: (mod_fastcgi.c.2702) FastCGI-stderr: Run
2016-12-25 21:19:23: (mod_fastcgi.c.2702) FastCGI-stderr:   git config --global user.email "you@example.com"
2016-12-25 21:19:23: (mod_fastcgi.c.2702) FastCGI-stderr:   git config --global user.name "Your Name"
2016-12-25 21:19:23: (mod_fastcgi.c.2702) FastCGI-stderr: to set your account's default identity.
2016-12-25 21:19:23: (mod_fastcgi.c.2702) FastCGI-stderr: Omit --global to set the identity only in this repository.
2016-12-25 21:19:23: (mod_fastcgi.c.2702) FastCGI-stderr: fatal: unable to auto-detect email address (got 'www-data@catbug.(none)')
2016-12-25 21:19:23: (mod_fastcgi.c.2702) FastCGI-stderr: ' in /srv/edda/lib/plugins/gitbacked/lib/Git.php:317
2016-12-25 21:19:23: (mod_fastcgi.c.2702) FastCGI-stderr: Stack trace:
2016-12-25 21:19:23: (mod_fastcgi.c.2702) FastCGI-stderr: #0 /srv/edda/lib/plugins/gitbacked/lib/Git.php(332): GitRepo->run_command('/usr/bin/git --...')
2016-12-25 21:19:23: (mod_fastcgi.c.2702) FastCGI-stderr: #1 /srv/edda/lib/plugins/gitbacked/lib/Git.php(398): GitRepo->run('commit -av -m '...')
2016-12-25 21:19:23: (mod_fastcgi.c.2702) FastCGI-stderr: #2 /srv/edda/lib/plugins/gitbacked/action/editcommit.php(85): GitRepo->commit('Wiki page start...')
2016-12-25 21:19:23: (mod_fastcgi.c.2702) FastCGI-stderr: #3 /srv/edda/lib/plugins/gitbacked/action/editcommit.php(197): action_plugin_gitbacked_editcommit->commitFile('/srv/edda/data/...', 'Wiki page start...')
2016-12-25 21:19:23: (mod_fastcgi.c.2702) FastCGI-stderr: #4 /srv/edda/inc/events.php(211): action_plugin_gitbacked_editcommit->handle_io_wikipage_write(Object(Doku_Event), NULL)
2016-12-25 21:19:23: (mod_fastcgi.c.2702) FastCGI-stderr: #5 /srv/edda/inc/events.php(79): Doku_Event_H in /srv/edda/lib/plugins/gitbacked/lib/Git.php on line 317

 wednesday@catbug  /srv/edda/data/gitrepo/.git   master  cat /var/www/.gitconfig 
[user]
        email = devzorro@gmail.com
        name = Last Wednesday
[push]
        default = simple
