### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'Exception' with message 'fatal: ...pages/User/beber.txt: '...pages/User/beber.txt' is outside repository

### ISSUE THREAD

**Issue by bjacquin** [woolfg/dokuwiki-plugin-gitbacked#43]
Hi,

I've made of update of dokuwiki-plugin-gitbacked from 2012-10-31 to 2016-08-14 and since then, PHP is throwing error such as:

```
2017-10-18T17:48:16-07:00 user.notice e5-web1 apache2[7335]: PHP Fatal error:  Uncaught exception 'Exception' with message 'fatal: /srv/web/enlightenment.org/public_html/data/www-content/pages/User/beber.txt: '/srv/web/enlightenment.org/public_html/data/www-content/pages/User/beber.txt' is outside repository
' in /srv/web/enlightenment.org/public_html/lib/plugins/gitbacked/lib/Git.php:317
Stack trace:
#0 /srv/web/enlightenment.org/public_html/lib/plugins/gitbacked/lib/Git.php(332): GitRepo->run_command('/usr/bin/git --...')
#1 /srv/web/enlightenment.org/public_html/lib/plugins/gitbacked/lib/Git.php(365): GitRepo->run('add /srv/web/en...')
#2 /srv/web/enlightenment.org/public_html/lib/plugins/gitbacked/action/editcommit.php(84): GitRepo->add('/srv/web/enligh...')
#3 /srv/web/enlightenment.org/public_html/lib/plugins/gitbacked/action/editcommit.php(197): action_plugin_gitbacked_editcommit->commitFile('/srv/web/enligh...', 'Wiki page beber...')
#4 /srv/web/enlightenment.org/public_html/inc/events.php(211): action_plugin_gitbacked_editcommit->handle_io_wikipage_write(Object(Doku_Event), NUL in /srv/web/enlightenment.org/public_html/lib/plugins/gitbacked/lib/Git.php on line 317
```

The diff between the two revision is very limited, I'm not sure to undestand why $filePath is now different.

Is there any other information that I could provide ?

**Comment by woolfg** [comment]
Have you checked all paths in the configuration?

**Comment by bjacquin** [comment]
I did yes, all is fine and works like a charm by just reverting the code

**Comment by ajwillia-ms** [comment]
I see this problem too - it seems like the paths are switching from relative to absolute.
All my configuration is in relative paths as it has been for years - does the new version only work with absolute paths perhaps?

**Comment by woolfg** [comment]
does it work for you with absolute paths, as far as I can remember we haven't changed that. Also did a quick look at the changes...

**Comment by woolfg** [comment]
closed as not active for a while. feel freee to reopen.
